
CREATE TABLE IF NOT EXISTS `Comment` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `Name` VARCHAR(128) NOT NULL,
  `Mail` VARCHAR(128) NOT NULL,
  `Comment` MEDIUMTEXT NOT NULL,
  `CreatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP
);