CREATE TABLE IF NOT EXISTS `signup` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `First_Name` VARCHAR(128) NOT NULL,
  `Last_Name` VARCHAR(128) NOT NULL,
  `companyname` VARCHAR(128) NOT NULL,
  `Email` VARCHAR(128) NOT NULL,
  `Password` VARCHAR(128) NOT NULL,
  `Confirm_Password` VARCHAR(500) NOT NULL,
  `website` VARCHAR(128) NOT NULL,
  `CreatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
    Unique Key Unique_Email (Email)
);